#ifndef BLACKJACKSIMULATION_STRATEGY_H
#define BLACKJACKSIMULATION_STRATEGY_H

typedef enum {
    HIT,
    STAND,
    DOUBLE_OR_HIT,
    DOUBLE_OR_STAND,
    SPLIT,
    SURRENDER_OR_HIT,
    SURRENDER_OR_STAND,
} Decision;

#endif //BLACKJACKSIMULATION_STRATEGY_H